### ISSUE TITLE
Cannnot compile

### ISSUE THREAD

**Issue by chekanov** [slaclab/lcdd#2]
Hi, Jeremy

 I cannot compile it using "cmake":

 lcdd/core/GeometryManager.cc:8:39: fatal error: G4Processor/GDMLProcessor.h: No such file or directory
 #include "G4Processor/GDMLProcessor.h"
                                       ^
compilation terminated. 

My previous gdml compilation using cmake creates only "lib" director, but there is not "include"  directory where "GDMLProcessor.h" must be located

best, Sergei

**Comment by JeremyMcCormick** [comment]
This looks like a problem with out of source builds.  I need to have it copy the header files into the GDML install dir.

For now, if you install GDML into the source dir (the one from checking out of master) it should work fine.

**Comment by JeremyMcCormick** [comment]
This should be fixed now, but you need to rebuild GDML.  There should now be an `include` dir in the GDML installation dir containing the header files which LCDD will find.

**Comment by JeremyMcCormick** [comment]
Fixed in PR #3.
